name: Slack Notification

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify-on-label:
    runs-on: ubuntu-latest
   
    
    steps:
      - name: check PR label
        uses: actions/checkout@v2

      - name: get labels list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        id: get_pr_labels_list
        run: |
         PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN {FS="/"} {print $3}')
          GIT_HUB_TOKEN=${{secrets.GITHUB_TOKEN}}
          labels=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                      https://api.github.com/repos/Aishwarya-keshavaReddy/GHA-hackathon/issues/$PR_NUMBER/labels)
          echo "labels: $lables"

      - name: Check PR label
        id: check_label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         echo " pr labels:  $(gh api --jq '.labels.[].name' /repos/Aishwarya-keshavaReddy/GHA-hackathon/pulls/${{ github.event.number }})"
        # run: echo "::set-output name=has_label::$(jq -r '.label.name' $GITHUB_EVENT_PATH | grep -q 'critical' && echo true || echo false)"
      
      # - name: Send Slack notification
      #   # if: steps.check_label.outputs.has_label == 'true'
      #   run: |
      #     curl -X POST --data-urlencode "payload={\
      #       \"channel\": \"#common-sense-build-deploy-notifications\", \
      #       \"username\": \"Aish-Testing\", \
      #       \"text\": \"A PR *${{ github.event.pull_request.title }}* with Critical status has been opened, Please review Asap!\", \
      #       \"icon_emoji\": \":github-actions:\" \
      #     }" ${{ secrets.SLACK_WEBHOOK_URL }}
