name: Slack Notification

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify-on-label:
    runs-on: ubuntu-latest
   
    
    steps:
      - name: check PR label
        uses: actions/checkout@v2

      - name: get labels list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        id: get_pr_labels_list
        run: |
         PR_NUMBER=${{ github.event.pull_request.number }}
          labels_list=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                      https://api.github.com/repos/Aishwarya-keshavaReddy/GHA-hackathon/issues/$PR_NUMBER/labels)
          labels=$(echo "$labels_list" | jq -r '.[] | .name')       
          notify_labels=("critical" "major" "Highest")
          should_notify=false
          for notify_label in "${notify_labels[@]}"; do
            if [[ "$labels" == *"$notify_label"* ]]; then
              should_notify=true
              echo "::set-output name=label_name::$notify_label"
              break
            fi
          done
          echo "::set-output name=should_notify::$should_notify"
          echo " should notify: $should_notify"

      - name: Send Slack notification
        if: steps.get_pr_labels_list.outputs.should_notify == 'true'
        run: |
          curl -X POST --data-urlencode "payload={\
            \"channel\": \"#common-sense-build-deploy-notifications\", \
            \"username\": \"PR REVIEW REQUIRED\", \
            \"text\": \" Hey! <!channel> A PR <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> with priority: *${{steps.get_pr_labels_list.outputs.label_name}}* has been opened, Please review Asap!\", \
            \"icon_emoji\": \":github-actions:\" \
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
