name: Slack Notification

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify-on-label:
    runs-on: ubuntu-latest
   
    
    steps:
      - name: check PR label
        uses: actions/checkout@v2

      - name: Check PR label
        id: check_label
        run: |
         echo " pr labels:  $(gh api --jq '.labels.[].name' /repos/Aishwarya-keshavaReddy/GHA-hackathon/pulls/${{ github.event.number }})"
        # run: echo "::set-output name=has_label::$(jq -r '.label.name' $GITHUB_EVENT_PATH | grep -q 'critical' && echo true || echo false)"
      
      - name: Send Slack notification
        # if: steps.check_label.outputs.has_label == 'true'
        run: |
          curl -X POST --data-urlencode "payload={\
            \"channel\": \"#common-sense-build-deploy-notifications\", \
            \"username\": \"Aish-Testing\", \
            \"text\": \"A PR *${{ github.event.pull_request.title }}* with Critical status has been opened, Please review Asap!\", \
            \"icon_emoji\": \":pr-open:\" \
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
